# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# -- Source Prezto -- #
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# -- Aliases -- #

#alias ls="colorls --sd -A"

PRIV="sudo"

alias c="clear"
alias q="exit"
alias hd="hexdump -C"
alias default-apps="clear && ~/.scripts/default-apps/launch && ~/.scripts/default-apps/launch -e"
alias pacrem="$PRIV pacman -Rcns"
alias pill="sudo powerpill -S"
alias up="sudo pacman -Sy && sudo powerpill -Su && yay"
alias install="yay -S"
alias search="yay -Ss"
alias yayupd="yay -Sy"
alias yayupg="yay -Syu"
alias remove="yay -Rcns"
alias emergeins="$PRIV emerge -av"
alias emergepv="$PRIV emerge -pv"
alias emergeupd="$PRIV emaint -a sync"
alias emergeupg="$PRIV emerge -av --update --deep --changed-use @world"
alias emergedepc="$PRIV emerge --depclean -av"
alias emergenuse="$PRIV emerge -av --update --newuse --deep @world"
alias emergecuse="$PRIV emerge -av --update --changed-use --deep @world"
alias ecleandist="$PRIV eclean-dist --deep"
alias ecleankern="$PRIV eclean-kernel -n 3"
alias rc-service="$PRIV rc-service"
alias rc-update="$PRIV rc-update"
alias pingoogle="ping 8.8.8.8"
alias trimall="$PRIV fstrim -va"
alias nanosu="$PRIV nano"
alias nvimsu="$PRIV nvim"
alias off="systemctl poweroff -i"
alias boot="systemctl reboot -i"
alias paste="curl -F 'sprunge=<-' http://sprunge.us"
alias ydl="youtube-dl -x --audio-format mp3 --prefer-ffmpeg"
alias won="wg-quick up wgcf-profile"
alias woff="wg-quick down wgcf-profile"
alias wforce="sudo rm -rf wgcf-profile.conf && wgcf generate && sudo rm -rf /etc/wireguard/wgcf-profile.conf && sudo cp wgcf-profile.conf /etc/wireguard"

# -- Colorscheme -- #
# Import colorscheme from 'wal' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
(cat ~/.cache/wal/sequences &)

# Alternative (blocks terminal for 0-3ms)
cat ~/.cache/wal/sequences

# To add support for TTYs this line can be optionally added.
source ~/.cache/wal/colors-tty.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
