#!/bin/sh
   cd "$HOME/.config/conky"
   conky -c "$HOME/.config/conky/Process" &
   cd "$HOME/.conky/Sirius"
   conky -c "$HOME/.conky/Sirius/Sirius" &
   cd "$HOME/.conky/spoclo/spotify-top"
   conky -c "$HOME/.conky/spoclo/spotify-top/spoclo_rightedge.conky"
   exit 0
